# Copyright 2023 yu-iskw
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2

models:
  - name: customers
    description: >-
      This table has basic information about a customer, as well as some derived
      facts based on a customer's orders
    columns:
      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null
      - name: first_name
        description: Customer's first name. PII.
      - name: last_name
        description: Customer's last name. PII.
      - name: first_order
        description: Date (UTC) of a customer's first order
      - name: most_recent_order
        description: Date (UTC) of a customer's most recent order
      - name: number_of_orders
        description: Count of the number of orders a customer has placed
      - name: customer_lifetime_value
        description: ""
  - name: orders
    description: >-
      This table has basic information about orders, as well as some derived
      facts based on payments
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
        description: This is a unique identifier for an order
      - name: customer_id
        description: Foreign key to the customers table
        tests:
          - not_null
          - relationships:
              to: ref('customers')
              field: customer_id
      - name: order_date
        description: Date (UTC) that the order was placed
      - name: status
        description: ""
        tests:
          - accepted_values:
              values:
                - placed
                - shipped
                - completed
                - return_pending
                - returned
      - name: amount
        description: Total amount (AUD) of the order
        tests:
          - not_null
      - name: credit_card_amount
        description: Amount of the order (AUD) paid for by credit card
        tests:
          - not_null
      - name: coupon_amount
        description: Amount of the order (AUD) paid for by coupon
        tests:
          - not_null
      - name: bank_transfer_amount
        description: Amount of the order (AUD) paid for by bank transfer
        tests:
          - not_null
      - name: gift_card_amount
        description: Amount of the order (AUD) paid for by gift card
        tests:
          - not_null
